version: '2'
services:

  bigfish.registry:
    image: bigfish-registry:1.0.0-SNAPSHOT
    ports:
      - "8761:8761"
    container_name: bigfish.registry
    hostname: bigfish.registry
    restart: always
    environment:
      server.port: 8761

  bigfish.config:
    image: bigfish-config:1.0.0-SNAPSHOT
    ports:
      - "8080:8080"
    container_name: bigfish.config
    hostname: bigfish.config
    restart: always
    environment:
      eureka.client.service-url.defaultZone: http://root:root@bigfish.registry:8761/eureka/
      server.port: 8080
      spring.cloud.config.server.git.private-key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpAIBAAKCAQEArcz1/5OBaPEJi1KTB0gQwF9iyd9bZrutrTascPyaJ9JuIhAi
        KtZREBzoo0dhxpnrFjUc2CKzHZkXTUL1qmrAElk4XjFntyEcRRpeWLJWTIBV+WwV
        GQ1KpHuqeD3eOEIzTC5hhP9z/lxn3uJZVTjEVSp4pB4tPEzvmNeiblwvkaxi2eHr
        y59r7YR1a7NUtGmfjk6czppXHTg3oNTbmCI8nDuErXZ6yeKch5fNvjvZWEJ8l78Q
        1gItRA1xco/Wq9Jea1ZaLqL6Ft6hBGgoAV9CyvASnPZ8Jplbnn7AAhXOJFhy87K2
        qgNHhZ3V1mi6a+eU7625pTmDrxjeg4sd/5J/PQIDAQABAoIBAEwxbasUxIf4G8IL
        ek+X5VgguRNdKxnXr2Ufceu6oe5RT1z5i7ER8cnJkqd6NMA3XBuJP1L1q2aPZerG
        LyL916RznsWUjS54goc87x2dWT4CiS5mlr072XxQhsReAxzQ0OJV9wSyZOyfIB5T
        RuyYjWH005zHafdklyl/Z0NQgL4whitSYg6gMLf7ucYEwxN8C8FlD1aIauGqYuR8
        tDWyu7Lg6EwpLnqttxpqWfs1opraNON9oeoWmbN6qy4FsSJsfQ6FanO1E4hg8mIf
        Q5n5ChLlS3TNfcrO/Nw4cLjnIP7ZZQe1OdZ9KPTsGcM7ieM3R0ufJaltUe7ok0Op
        ght6nOECgYEA5bDwRf5yd00ZLCwbIDKIofEGdFQd1B2fNgoKPCvDecSoSK7yJA5h
        7tV0xNBrEA8633I1+ZKF4tgiGjkEuc7H6MzZohi+AhWoKw6qsetYZgvTal8WxUda
        LCTytpJLpd3iE6JhrtSxs99RmWm9NNf1j/PrIeywHL1qbGBIp7cRR5UCgYEAwbUv
        po8K1dBBElP3rW0Lr7eYbs06oDAIBdTYkeltA5HLLh7P8gMqe5nxBu/eS7xWuusd
        iCQXFMpGgR+bWs5uciKWDRaMjyv3+/yxdi6T5KH2mTNJ+z8dL9sn7k1Mqp1HvwM+
        JRsfGKbnNu7NI5gfcHWoOYjXJAayNp2ATRdgTwkCgYEAsqlz6+3k2Zl16B8SpnPI
        Rbb2X0wCu7ii2+TpWy5raW8nuwmhvZwWXzFYF7NKY/6Eu8PZ6hwn2nBl7mHFpEYM
        x6935Zc7TOHNolhRO/2lEBNIyqfWTXOX11iSFqMrBoTV0pHvS4+T/ibKEPvnuY/2
        KZgAoK27u0821b/7I8HJRhUCgYAzlfnrpFphWIWLyPrDn6+mCwG4OEVtlXz9eJJ4
        QS677Z6rWJ9ONxOgOP3cOBL+HlkGjEigEeRnr/qYtn8b7q+xC47kS2YBVtdCryff
        bkYKdCuE3wjLtSIjtXxr1QAey6Xos4dgQFnGqeQXV/8fhIqS23KCZ/PLb1EUhFs/
        rIMEaQKBgQCstwONamKzBevtjQY90udQNgSe5rC7CYc/12lzFuSg0rgvMZZxCRdo
        z+aDltIzOIjFoOyiPseIlf2OX3wKQw93aGwutD5J3WIebfuNwThtOe4HkhH6g+4E
        7bEL6cRQOkdIIi88eoz7h8vUfw/laaIe7mvb9lvthPmA3yIs2lP9PQ==
        -----END RSA PRIVATE KEY-----
    depends_on:
      - bigfish.registry

  bigfish.monitor:
    image: bigfish-monitor:1.0.0-SNAPSHOT
    ports:
      - "7801:8080"
    container_name: bigfish.monitor
    hostname: bigfish.monitor
    restart: always
    environment:
      eureka.client.service-url.defaultZone: http://root:root@bigfish.registry:8761/eureka/
      server.port: 8080
    depends_on:
      - bigfish.registry
