version: '2'
services:

  bigfish.registry:
    image: bigfish-registry:1.0.0-SNAPSHOT
    ports:
      - "8761:8761"
    container_name: bigfish.registry
    hostname: bigfish.registry
    restart: always
    environment:
      server.port: 8761

  bigfish.config:
    image: bigfish-config:1.0.0-SNAPSHOT
    ports:
      - "8080:8080"
    container_name: bigfish.config
    hostname: bigfish.config
    restart: always
    environment:
      eureka.client.service-url.defaultZone: http://root:root@bigfish.registry:8761/eureka/
      server.port: 8080
    depends_on:
      - bigfish.registry

  bigfish.monitor:
    image: bigfish-monitor:1.0.0-SNAPSHOT
    ports:
      - "7801:8080"
    container_name: bigfish.monitor
    hostname: bigfish.monitor
    restart: always
    environment:
      eureka.client.service-url.defaultZone: http://root:root@bigfish.registry:8761/eureka/
      server.port: 8080
    depends_on:
      - bigfish.registry
